name: Website request
description: Request a website
title: "[Website] "
labels: ["website"]
assignees:
- zDania4
body:
  - type: checkboxes
    attributes:
      label: The website in question is NOT listed in the blocklist
      description: |
        Tick the box if the website is NOT already listed in the blocklist. If the website is listed and you're experiencing issues, please use "Bug report" instead.
      options:
        - label: The website is NOT listed in the blocklist
          required: false

  - type: textarea
    id: url
    attributes:
      label: Website URL
      description: |
       The URL of the website in question.
      placeholder: |
          Please include the entire URL:
          https://example.com/subpage/1234.html
          https://example.com/video?id=1234
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Describe issues
      description: |
       Please describe any issues you have on the website, any specific devices you encounter these issues on and why you wish it to be included in the blocklist. Please include as much detail as possible.
    validations:
      required: true
